### ISSUE TITLE
I wish to know in which file to put this instruction

### ISSUE THREAD

**Issue by noellaby** [shashankvaibhav/Freshchat-android-ReactNative#15]
I am new in the development with React Native, I wish to know in which file to put this instruction

5 - add this in your MainApplication package list.
new FreshChatReactPackage()

**Comment by shashankvaibhav** [comment]
There is a MainApplication.java file. Write down inside method getPackages.
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
           new MainReactPackage(),
          new FreshChatReactPackage(),
)}

**Comment by noellaby** [comment]
Thank You @shashankvaibhav , i see file on directory : android\app\src\main\java\com\katika\MainApplication.java
