### ISSUE TITLE
Error Build Apps : error: cannot find symbol new FreshChatReactPackage()

### ISSUE THREAD

**Issue by noellaby** [shashankvaibhav/Freshchat-android-ReactNative#17]
When I run the react-native run-android command, I have this error:

error : J:\Projet\foongon\react native\Entreprise\Katika\android\app\src\main\java\com\katika\MainApplication.java:26: error: cannot find symbol
                  new FreshChatReactPackage()
                      ^
  symbol: class FreshChatReactPackage
1 error
:app:compileDebugJavaWithJavac FAILED

What can be done to solve this problem ?

Link Image Error : https://image.noelshack.com/fichiers/2018/20/7/1526795123-erreur.png
Link My File  MainApplication : https://image.noelshack.com/fichiers/2018/20/7/1526795455-mainapplication.png

**Comment by shashankvaibhav** [comment]
Can you post the screenshot for mainapplication.java file?

**Comment by noellaby** [comment]
Link My File MainApplication : https://image.noelshack.com/fichiers/2018/20/7/1526795455-mainapplication.png

**Comment by shashankvaibhav** [comment]
Did you import FreshChatReactPackage in your mainapplication file?

**Comment by noellaby** [comment]
How to Import FreshChatReactPackage in mainapplication file ?

**Comment by shashankvaibhav** [comment]
import com.android.freshchatSdk.FreshChatReactPackage;

**Comment by noellaby** [comment]
Thanks
