### ISSUE TITLE
Build failed android

### ISSUE THREAD

**Issue by herarya** [shashankvaibhav/Freshchat-android-ReactNative#4]
hi @shashankvaibhav FreshChatReactPackage.java:27: error: method does not override or implement a method from a supertype

**Comment by shashankvaibhav** [comment]
Yay! The library was made for the older version of react native which required that conflicting method.
In order to make it work on new react native versions just remove the conflicting method and eveything would work

**Comment by shashankvaibhav** [comment]
Please close the issue if problem is solved.

**Comment by herarya** [comment]
@shashankvaibhav ok thanks , worked
