### ISSUE TITLE
compile Error

### ISSUE THREAD

**Issue by lovelyKarthi** [shashankvaibhav/Freshchat-android-ReactNative#5]
1 error
:react-native-android-library-freshchat-sdk:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-android-library-freshchat-sdk:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I have react native 0.51.0 and react-native-android-library-freshchat-sdk 2.0.0

**Comment by shashankvaibhav** [comment]
The library was made for the older version of react native which required a method inside FreshChatReactPackage.java. 

@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

In order to make it work on new react native versions just remove the conflicting method and everything would work.

**Comment by lovelyKarthi** [comment]
Same error occurred
**Removed**
  // @Override
    // public List<Class<? extends JavaScriptModule>> createJSModules() {
    //     return Collections.emptyList();
    // }
**added**
    @override
        public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

**Comment by lovelyKarthi** [comment]
I removed the method

@override
public List<Class<? extends JavaScriptModule>> createJSModules() {
return Collections.emptyList();
}

 it got fixed Thanks
