### ISSUE TITLE
FAQ section unavailable

### ISSUE THREAD

**Issue by pragadeesh0106** [shashankvaibhav/Freshchat-android-ReactNative#6]
After init of fresh chat i called the showFAQs function and it opens a toast saying "uh-uh FAQ section not available".

**Comment by shashankvaibhav** [comment]
Hello @pragadeesh0106 If FAQs are there it will be shown. You need to contact freshchat and make sure you have your faqs setup.

If FAQs are there with freshchat, you will have to call faqs and conversation method after a little delay after init.
Freshchat takes little time to initialize the user and show them the faqs. I guess
